### ISSUE TITLE
Uncaught Error: Cannot find module 'xxx.vue'

### ISSUE THREAD

**Issue by laosb** [Akryum/meteor-vue-component#101]
> The initial issue (`Uncaught ReferenceError: _h is not defined`) was solved by updating both `vue` and `akryum:vue-component`.

I'm experiencing `Uncaught Error: Cannot find module './userLink.vue'` on production.

It happened only in production bundle, even not happening in `meteor --production` on my dev box.

I figured out the exact commit from which we start to have this weird problem: it was just adding a not-yet-finished vue component which is not imported by any files at all. I can't present it there since it is in a private repo, but there is the online version of the last working commit: https://immortal.work/ alongside with the first not working version (our staging server): http://iw.daoapp.io/. You can see the problem on the latter.

Thank you for taking time looking at this problem in advance.

**Comment by Akryum** [comment]
Please try updating all your meteor packages to their latest version and Vue to `2.1.8` ([related to this](https://github.com/vuejs/vue/releases/tag/v2.1.7)). If you still have the error, could you list all the versions here?

**Comment by laosb** [comment]
Updating to Vue 2.1.8 didn't solve the problem. I'm updating your packages but not updating aldeed's packages since it will take some time to migrate. Will report soon.

**Comment by laosb** [comment]
Things are getting worse as it complains about unable to find vue component modules.

**Comment by gustogummi** [comment]
It's not "getting worse", it's actually "getting better". Your app resolved the `_h is not defined` issue and moved on, then found another issue and that's why you get the new error message.

**Comment by MartinBucko** [comment]
+1 on production build @latest version

```
meteor build --directory $BUILD_DIR --architecture=os.linux.x86_64 --server-only 
```

in console log:
```
ed048c2….js?meteor_js_resource=true:9 Uncaught Error: Cannot find module '/imports/ui/components/NominationAdd.vue'
``
in dev run works all correctly..

**Comment by MartinBucko** [comment]
same bug on  `meteor run --production`

**Comment by laosb** [comment]
Not sure about what happening. It seems that it didn't include nested imports?

**Comment by Akryum** [comment]
I'm getting a strange Meteor error when building the example app:

```
 Attempting to combine different files:
{ type: 'js',
  sourcePath: 'client/ui/MyButton.vue',
  servePath: 'client/ui/MyButton.vue',
  installPath: 'client/ui/MyButton.vue',
  deps: { './MyButton.vue.css': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 4d 79 42 75 74 74 6f 6e 2e 76 75 65 2e 63 73 73 22 29 3b 0a>,
  hash: '87396daab2a8f710bd9c28aafab7e060bd574270' }
{ type: 'js',
  data: <Buffer 76 61 72 20 5f 5f 76 75 65 5f 73 63 72 69 70 74 5f 5f 2c 20 5f 5f 76 75 65 5f 74 65 6d 70 6c 61 74 65 5f 5f 3b 5f 5f 76 75 65 5f 73 63 72 69 70 74 5f ... >,
  sourcePath: 'client/ui/MyButton.vue',
  targetPath: 'client/ui/MyButton.vue',
  servePath: '/client/ui/MyButton.vue',
  hash: '1ce08740ecc69a68045f3e5055bec1d70ef539b0',
...
```

**Comment by Akryum** [comment]
This seems related to the fact each `inputFile` is adding both JavaScript and Style. Commenting either `addJavaScript` or `addStylesheet` resolves this.

**Comment by laosb** [comment]
I'm not sure if your problem is related to this one. Before you ask, I didn't update my packages. After your ask, I did a manual update:

```
--- a/.meteor/versions
+++ b/.meteor/versions
@@ -1,11 +1,11 @@
 accounts-base@1.2.14
 accounts-password@1.3.3
 akryum:npm-check@0.0.3
-akryum:vue@1.2.1
+akryum:vue@1.2.2
 akryum:vue-blaze-template@0.0.3
-akryum:vue-component@0.7.7
-akryum:vue-component-dev-client@0.2.1
-akryum:vue-component-dev-server@0.0.2
+akryum:vue-component@0.8.1
+akryum:vue-component-dev-client@0.2.3
+akryum:vue-component-dev-server@0.0.4
 akryum:vue-less@0.0.4
 alanning:roles@1.2.15
 aldeed:collection2@2.10.0
```

**Comment by Akryum** [comment]
And you still have you initial issue?

**Comment by laosb** [comment]
I'm still experiencing `Uncaught Error: Cannot find module './userLink.vue'` on production. Everything goes well on my dev box with regular `meteor`.

**Comment by laosb** [comment]
I've updated this issue to the "can't find module" one since that's what we're talking about now.

**Comment by laosb** [comment]
@Akryum I did a little investigation on this problem. I checked out your vue2 example, and did get your `Attempting to combine different files:` error. It only happens when the component is not in `/imports`. I deleted MyButton.vue and it complains about "can't find modules" again. So basically your `Attempting to combine different files:` error might not be related to the can't find modules error.

I tried to downgrade your package in my app, but it doesn't work from 0.7.7 to 0.8.1. That's weird since I started to use your package since 0.7.7, but it did work at the first. I'm thinking about downgrading Vue.

**Comment by laosb** [comment]
Downgrading Vue to even 2.0.3 doesn't work. That was the first version I used in my project.

**Comment by Akryum** [comment]
Did you try downgrading Meteor?

**Comment by MartinBucko** [comment]
@Akryum i all ready try it with `meteor run --production --release 1.4.1` on example app but with same error in browser...  i was unable to run `meteor run --production --release 1.3` due startup error `Unexpected mongo exit code 100.`

**Comment by MartinBucko** [comment]
In my comparison from working production versions it's look like this is only affected packages:

```
blaze            upgraded from 2.2.0 to 2.2.1 
modules-runtime  upgraded from 0.7.7 to 0.7.8
 ``` 

meteor was on always on v1.4.2.3

**Comment by MartinBucko** [comment]
May be some related changes in meteor repo.. 

https://github.com/meteor/meteor/commit/2eab0b2bf4d635c0a7d8b3f2b1569e03b73a4325

**Comment by laosb** [comment]
Meteor version was always on v1.4.2.3 +1

I notice that this problem happens even before I updating to `modules-runtime@0.7.8`.

**Comment by MartinBucko** [comment]
This changes helps me to build my app to production:

```diff
diff --git a/.meteor/packages b/.meteor/packages
index 4ce677f..929902b 100644
--- a/.meteor/packages
+++ b/.meteor/packages
@@ -14,7 +14,7 @@ tracker@1.1.1                 # Meteor's client-side reactive programming librar
 standard-minifier-css@1.3.2   # CSS minifier run for production mode
 standard-minifier-js@1.2.1    # JS minifier run for production mode
 es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
-ecmascript@0.6.1              # Enable ECMAScript2015+ syntax in app code
+ecmascript              # Enable ECMAScript2015+ syntax in app code
 
 static-html@1.1.12_1
 check@1.2.4
diff --git a/packages/vue-component/package.js b/packages/vue-component/package.js
index 02f2f09..19c8394 100644
--- a/packages/vue-component/package.js
+++ b/packages/vue-component/package.js
@@ -9,9 +9,9 @@ Package.describe({
 Package.registerBuildPlugin({
   name: "vue-component",
   use: [
-    'ecmascript@0.4.4',
-    'caching-compiler@1.0.5',
-    'babel-compiler@6.8.0'
+    'ecmascript',
+    'caching-compiler',
+    'babel-compiler'
   ],
   sources: [
     'plugin/regexps.js',
diff --git a/packages/vue-component/plugin/vue-compiler.js b/packages/vue-component/plugin/vue-compiler.js
index f8bf066..5d9c6e3 100644
--- a/packages/vue-component/plugin/vue-compiler.js
+++ b/packages/vue-component/plugin/vue-compiler.js
@@ -205,7 +205,8 @@ VueComponentCompiler = class VueCompo extends CachingCompiler {
     inputFile.addJavaScript({
       path: inputFile.getPathInPackage(),
       data: js,
-      sourceMap: compileResult.map
+      sourceMap: compileResult.map,
+      lazy: true
     });
 
     if (isDev) {
@@ -221,10 +222,11 @@ VueComponentCompiler = class VueCompo extends CachingCompiler {
   addStylesheet(inputFile, options) {
     const data = normalizeCarriageReturns(options.data);
     inputFile.addStylesheet({
-      path: inputFile.getPathInPackage() + '.css',
+      path: inputFile.getPathInPackage(),
       sourcePath: inputFile.getPathInPackage(),
       data: data,
-      sourceMap: options.map
+      sourceMap: options.map,
+      lazy: false
     });
   }
 }

````
But i see in vue-component-example app it need more to done with this patch...

**Comment by laosb** [comment]
Was all modifications required in this patch?

**Comment by laosb** [comment]
I wa thinking that removing versions pinned by releases would lead to an older version?

**Comment by MartinBucko** [comment]
@laosb in vue-compiler.js yes, lazy variable can be configured form type of input file but i think is always same on vue component .. 
In  Package.registerBuildPlugin -> use it need to figure correct packages version to sync with current Meteor build requirements i think...

.. no it sync top level version from meteor in dev stage, but it will be required on meteor publish package (meteor-vue-component)

**Comment by MartinBucko** [comment]
@Akryum lazy variable and removing css extennsion solve https://github.com/meteor/meteor/issues/8222

**Comment by laosb** [comment]
I would try this this weekend...

**Comment by laosb** [comment]
With @Akryum 's recent commit and `lazy: true` on `addJavascript`, problem solved for me. But it's true that `.vue`s out of `imports/` won't be processed. For me it's OK.

**Comment by drantunes** [comment]
@laosb How are you doing each `import`?

For me the error `Uncaught Error: Cannot find module './XXX.vue'` persist in `--production`

**Comment by laosb** [comment]
Just as we usually do.

**Comment by drantunes** [comment]
So I tried a number of ways. I moved all the code to the `imports` folder, I did the manual imports, but in `--production` does not work.

**Comment by Akryum** [comment]
Could you try cloning the repo and putting the `packages/vue-component` folder into your app?

**Comment by drantunes** [comment]
Same error. I'll try again later.

**Comment by Akryum** [comment]
I have push a new `8.1.3` version that fixes the production mode only for explicitly imported vue files. An upstream fix will be released soon in meteor 1.4.2.4.

**Comment by drantunes** [comment]
I'll test 8.1.3. I changed my structure for explicitly imported vue files. 
Thanks @Akryum

**Comment by laosb** [comment]
@Akryum @drantunes it should be 0.8.3 I guess?

**Comment by Akryum** [comment]
I tested `meteor 1.4.2.4-rc.1` and it works with `lazy: false` for both auto and explicitly imported `.vue` files! :tada: 
https://github.com/meteor/meteor/issues/8222#issuecomment-277047445

**Comment by drantunes** [comment]
I updated meteor to `1.4.2.4-rc.1` and no problems to work with `0.8.3` release. But, when I updated the package to `0.8.4` or `0.8.5` the browser shows some erros. I tried add manually the package, but not worked too. 

![erros-when-update-to 0 8 4](https://cloud.githubusercontent.com/assets/1202936/22584065/8cf4be48-e9d7-11e6-8c19-779c1e7700e7.png)

**Comment by educob** [comment]
I am getting same exact error. 
I know the cause but not the solution. The files in node_modules are using "import ..." or "export .." instead of "const xxx = require ..." or "module.exports...". No module in node_modules is translated to older javascript.

No idea how to solve it. I followed this advice: [https://github.com/meteor-vue/vue-meteor/issues/url](url) but then links didn't work so I'm still trying to solve it.
